# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160322_2354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterSignUp',
            new_name='SignUp',
        ),
    ]
