# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20160330_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='tags',
            new_name='forum',
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
