# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20160423_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=150),
        ),
    ]
